[package]
name = "ktask"
version = "0.1.0"
edition = "2024"

[dependencies]
tungstenite = { version = "0.23", default-features = false, features = ["rustls-tls-native-roots", "handshake"] }
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-native-roots"] }
url = "2.4"
serde_json = "1.0"
webpki = "0.22.4"
rosc = "0.11.4"
rustls = "0.23.32"
prost = "0.13"
prost-types = "0.13"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
tonic = "0.12"
tokio = { version = "1.41", features = ["full"] }
tokio-stream = "0.1"
futures-core = "0.3"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
anyhow = "1.0"
axum = { version = "0.7", features = ["ws", "cors"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

[build-dependencies]
tonic-build = "0.12"
